default_install_hook_types: [pre-commit, post-commit]
repos:
  - repo: local
    hooks:
      - id: sync-requirements
        name: Sync requirements.txt with uv after commit
        entry: |
          bash -c 'uv export --format=requirements.txt --no-hashes --no-annotate --no-header > cdk/lambda/requirements.txt'
          if ! git diff --quiet cdk/lambda/requirements.txt; then
              git add cdk/lambda/requirements.txt
              git commit --amend --no-edit --no-verify
          fi
        language: system
        always_run: True
        verbose: True
        files: '(pyproject\.toml|uv\.lock)$'
        pass_filenames: false
        stages: ['post-commit']