[project]
name = "mursst-icechunk-updater"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.38.46",
    "dask>=2025.7.0",
    "earthaccess>=0.13.0",
    "h5netcdf>=1.6.3",
    "icechunk>=1.0.0",
    "requests>=2.25.0",
    "virtualizarr",
    "zarr>=3.1.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.0",
]

[tool.uv.sources]
virtualizarr = { git = "https://github.com/zarr-developers/VirtualiZarr.git", rev = "2e0b22822b51f1a9c8cbe08c791289e1fce895c3" }
