name: MUR-SST Ichchunk Updater

on:
  workflow_dispatch:
  release:
    types:
      - published
  push:
    branches:
      - main
    tags-ignore:
      - "*"
    paths:
      - ".github/workflows/*"
      - "cdk/**/*"
      - "tests/**/*"
      - "pyproject.toml"
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize
    paths:
      - ".github/workflows/*"
      - "cdk/**/*"
      - "tests/**/*"
      - "pyproject.toml"

defaults:
  run:
    shell: bash

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    needs: config
    steps:
      - uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "${{ vars.PYTHON_VERSION }}"

      - name: Install test requirements
        run: uv sync --all-groups

      - name: Run tests
        run: uv run pytest --ignore=test_integration_in_region.py

      - name: Check uv lockfile
        run: uv lock --check
  
  deploy-staging:
    # # Deploy to dev only on push (including merged PR) to `main` branch
    # if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'
    # for now deploy on any push 
    if: github.event_name == 'push'
    needs:
      - unit-tests
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
      PYTHON_VERSION: "${{ vars.PYTHON_VERSION }}"
    secrets: inherit

  deploy-prod:
    # Deploy to Prod only on publishing a release (tag) on `main` branch
    if: github.event_name == 'release' && github.event.action == 'published'
    needs:
      - unit-tests
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
      PYTHON_VERSION: "${{ vars.PYTHON_VERSION }}"
    secrets: inherit